# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15, verbose_name='\u7ec4\u540d\u79f0')),
                ('alias_name', models.CharField(max_length=15, verbose_name='\u7ec4\u522b\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7ec4',
                'verbose_name_plural': '\u7528\u6237\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, verbose_name='\u624b\u673a\u53f7')),
                ('id_number', models.CharField(max_length=20, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('credit_code', models.CharField(max_length=64, verbose_name='\u7edf\u4e00\u793e\u4f1a\u4fe1\u7528\u4ee3\u7801')),
                ('avatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5934\u50cf')),
                ('id_name', models.CharField(max_length=15, verbose_name='\u8eab\u4efd\u8bc1\u7528\u6237\u540d')),
                ('occupation', models.CharField(max_length=15, verbose_name='\u804c\u4e1a')),
                ('active', models.BooleanField(default=False, verbose_name='\u7528\u6237\u662f\u5426\u6fc0\u6d3b')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergroup', to='accounts.UserGroup', verbose_name='\u7528\u6237\u7ec4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=15, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('alias_name', models.CharField(max_length=15, verbose_name='\u89d2\u8272\u522b\u540d\u4e2d\u6587')),
                ('role_level', models.IntegerField(choices=[(1, 'super_admin'), (2, 'group_admin'), (3, 'group_user')], default=3, verbose_name='\u89d2\u8272\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u89d2\u8272',
                'verbose_name_plural': '\u7528\u6237\u89d2\u8272',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserRole', verbose_name='\u89d2\u8272'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.UserProfile', verbose_name='\u7ec4\u7ba1\u7406\u5458'),
        ),
    ]
