# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180314_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
    ]
