# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup', verbose_name='\u8d44\u4ea7\u6240\u5c5e\u533a\u57df'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='parms',
            field=django_mysql.models.JSONField(blank=True, default=dict, verbose_name='\u914d\u5957\u4fe1\u606f'),
        ),
    ]
