# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 17:37
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='instruction',
            field=django_mysql.models.JSONField(default=dict, verbose_name='\u8d44\u4ea7\u8bf4\u660e\u53c2\u6570'),
        ),
        migrations.AddField(
            model_name='category',
            name='parms',
            field=django_mysql.models.JSONField(default=dict, verbose_name='\u8d44\u4ea7\u914d\u5957\u4fe1\u606f\u53c2\u6570'),
        ),
        migrations.AddField(
            model_name='category',
            name='spot',
            field=django_mysql.models.JSONField(default=dict, verbose_name='\u8d44\u4ea7\u4eae\u70b9\u53c2\u6570'),
        ),
    ]
