# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_auto_20180316_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
    ]
